### ISSUE TITLE
undefined method `index' for true:TrueClass

### ISSUE THREAD

**Issue by jhuckabee** [stackify/stackify-api-ruby#11]
Trying to use the logger results in the following error for me (Ruby 2.1.5, Rails 3.2.21):

```
undefined method `index' for true:TrueClass
```

in [`lib/stackify/loger_client.rb`](https://github.com/stackify/stackify-api-ruby/blob/master/lib/stackify/logger_client.rb#L21).

This looks like an order of operations issues to me.

```ruby
if acceptable? level, ex.message && Stackify.working?
```
evaluates to

```ruby
if acceptable?(level, ex.message && Stackify.working?)
```

where I'm pretty sure you want

```ruby
if acceptable?(level, ex.message) && Stackify.working?
```
I think generally accepted Ruby style is to err on the side of using parentheses unless it's a method invocation involving an internal DSL or a method with keyword status. See https://github.com/bbatsov/ruby-style-guide.

I'm also surprised at the lack of tests for this library and curious if anyone is successfully using this in their Ruby/Rails projects. Stackify looks like a great solution on the surface, but I will admit after seeing the quality of this code my opinion has changed somewhat.

**Comment by eric-martin** [comment]
We will take a look.

**Comment by eric-martin** [comment]
Thanks for logging this. I've confirmed the bug and am retesting. I'll update this ticket when a new version (1.0.5) is available.

**Comment by eric-martin** [comment]
Version 1.0.6 fixes this issue and is not available. Thanks again.
