### ISSUE TITLE
logging configuration issues

### ISSUE THREAD

**Issue by meloredana** [stackify/stackify-api-ruby#15]
We Integrated stackify-api-ruby in our project and added the following initializer configuration for production:
```ruby
    Stackify.setup do |config|
	  config.api_key = 'KEY'
	  config.mode = :both
	  config.app_name = "appname"
	  config.env = :production
    end
```

When we log in to stackify we have log data for all our environments (test, development & production).
We only want to log production. Are we missing some configurations?

**Comment by ljthomas** [comment]
Thank you for your interest in Stackify! I don't believe you've missed any configuration items. If you'd like to not log on a specific deployed environment, then the best way would be to not deploy the Stackify configuration settings to that environment.

The "config.env" configuration setting is used internally by Stackify for categorization of a log once it has been received; however, this setting does not have any bearing on conditional logging at run-time within an application.

Definitely let us know if you have any further questions. 

Thank you!

**Comment by meloredana** [comment]
Thank you for clarifying that for me.
