### ISSUE TITLE
Stackify MySQL2 connection issue with RSpec

### ISSUE THREAD

**Issue by avinoth** [stackify/stackify-api-ruby#24]
```
Rails version: 4.2
Ruby version: 2.3.8
Stackify version: 1.0.14
```

I'm getting connection issues when using Stackify on our RSpec test suites.

This is the error when trying to run RSpec. I'm pretty sure it's from Stackify.

I tried debugging a bit and it seems to stem from https://github.com/stackify/stackify-api-ruby/blob/master/lib/stackify-api-ruby.rb#L109 when Stackify spawns a new thread while still holding a DB connection. 

I've also tried starting Stackify with async false, `Stackify.run(false)` but that triggers whole other issue which I'll file it as another report.

```
ActiveRecord::StatementInvalid: Mysql2::Error: This connection is in use by: #<Thread:0x00005570ab166b30@/usr/local/bundle/gems/stackify-api-ruby-1.0.14/lib/stackify-api-ruby.rb:109 sleep>: SHOW TABLES
```

**Comment by darinhoward** [comment]
Thank you for the bug report - we are looking into it now.

**Comment by darinhoward** [comment]
We will be testing this fix and planning on pushing to public repo on Monday.

**Comment by avinoth** [comment]
Thanks @darinhoward for swift fix!

**Comment by darinhoward** [comment]
@avinoth Please try version 1.0.15 (https://rubygems.org/gems/stackify-api-ruby/versions/1.0.15).  Let me know if this resolves your issue.
