### ISSUE TITLE
Fixnum#minutes conflicts with ActiveSupport's Fixnum#minutes

### ISSUE THREAD

**Issue by jgandt-hcs** [stackify/stackify-api-ruby#34]
https://github.com/stackify/stackify-api-ruby/blob/c1fd6a2346a6e6191695044362959dc294fdea39/lib/core_ext/fixnum.rb#L10

So if you require this gem after active support, it breaks active support. For example, the following would no longer work:
```
5.minutes.from_now
```
I suggest having this module detect what methods are already defined on Fixnum to avoid re-defining them. Or make the return value of this method compatible with active support.

Normally I wouldn't say you need to defer to another gem, but ActiveSupport was here first and it's ActiveSupport... so it's practically core lib.

**Comment by darinhoward** [comment]
@jgandt-hcs  Thank you for opening this issue - we will review and try and replicate.

**Comment by jgandt-hcs** [comment]
Hi! In addition, Fixnum is now a deprecated module in ruby 2.4. Thus I would expect our ruby 2.5 application not to include this file in the first place.

**Comment by darinhoward** [comment]
We are testing an update now  - see https://github.com/stackify/stackify-api-ruby/pull/36

**Comment by darinhoward** [comment]
Fix available in latest version https://rubygems.org/gems/stackify-api-ruby/versions/1.2.7
